### PR TITLE
handle when debugNeedsPaint is false

### PR DESCRIPTION
**Pull request by chokobole**

### CODE REVIEW

**Comment by ArkhipenkaPiotr** [comment]
Hi @chokobole! Please provide some information about your PR. What's the problem does this PR fix?

**Comment by chokobole** [comment]
Oh I ran into "'!debugNeedsPaint': is not true." error and applied the solution specified  https://stackoverflow.com/questions/57645037/unable-to-take-screenshot-in-flutter

**Review by ArkhipenkaPiotr — APPROVED** [review]

**Comment by ArkhipenkaPiotr** [comment]
Thank you, I'll release it

**Comment by ArkhipenkaPiotr** [comment]
Done, you can see your fix in 0.0.7 version

**Pull request merged**
